### ISSUE TITLE
Setup initial structure of repository

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation-services#1]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

The Repo should be used to create the Java based service that will host the Adoptium Documentation that is based on https://github.com/AdoptOpenJDK/website-adoptium-documentation
We decided that the service should be a Maven project based on Eclipse Microprofile 4.0 and Java 11 (17 if possible). I assume that we will host it on Wildfly. https://start.microprofile.io should be used to create the initial structure of the repo.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [x]  You did it 🎉 We will merge the fix in the master branch.
- [x]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by vanross** [comment]
@hendrikebbers Could you please add at least one file to this repository, a readme perhaps. Forking an empty repository is not supported.

**Comment by vanross** [comment]
@smlambert - sorry for the delay, ready for review.

**Comment by hendrikebbers** [comment]
PR: https://github.com/adoptium/documentation-services/pull/6
