### ISSUE TITLE
Add contributor info

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation-services#10]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**🚨About the Eclipse Contributor Agreement (ECA)**

Since Adoptium is a top level project of the [Eclipse Foundation](https://www.eclipse.org) only people that have (digitally) signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php) are allowed to contribute to Adoptium. This will automatically be checked in each pull request and pull requests from developers that have not signed the ECA can not be accepted. Luckily the workflow to digitally sign the ECA is very easy. All you need is an account at the Eclipse Foundation. Once you have an account you can easily sign the ECA [here](https://accounts.eclipse.org/user/eca). It's important that the email address of the Eclipse account must fit to the email address that is used in the GitHub account and commits.

**👾 Description of the issue**

We want to have a `CONTRIBUTING.md` file in the repo. A good example of such file can be found [here](https://github.com/adoptium/aqa-test-tools/blob/master/CONTRIBUTING.md). The must must contain the section regarding the "Eclipse Contributor Agreement".

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Check that you have signed the Eclipse Contributor Agreement (ECA) [here](https://accounts.eclipse.org/user/eca).
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [x]  You did it 🎉 We will merge the fix in the master branch.
- [x]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by MercheLorenzo** [comment]
Hello!
Could I work on this issue?
Thank you so much!
