### ISSUE TITLE
Get information of all authors for a documentation

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation-services#17]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

We want to honour all people that contributed to a documentation. By doing so we want to mention all the contributors on the bottom of a page as it can be seen in this mockup:
<img width="769" alt="contrib" src="https://user-images.githubusercontent.com/9443847/138054444-f79943b1-5962-4e8a-b1bc-6bdb968ed5c3.png">
To do so we need to receive the name, avatar image and the link to the GitHub profile for all contributors of a specific file. Looks like this can be achieved by using the GitHub Rest API as described [here](https://stackoverflow.com/questions/15831313/is-it-possible-to-get-commits-history-for-one-file-in-github-api). This pull request should add a service (CDI bean) that provides the functionality to get the described information for a specific file.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by hendrikebbers** [comment]
The PR https://github.com/adoptium/documentation-services/pull/18 provides the Document class. Once the PR is merged the users can be added as a set to that class.

**Comment by vanross** [comment]
Please review PR #38

**Comment by vanross** [comment]
Please review PR #39
