### ISSUE TITLE
Download Git repo content in a temp folder and provide static content

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation-services#4]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

The Repo should be used to create the Java based service that will host the Adoptium Documentation that is based on https://github.com/AdoptOpenJDK/website-adoptium-documentation
To use the documentation by this service the content of the master branch should be downloaded in a temp folder. This can be done by using the GitHub API or maybe JGit if that is needed for https://github.com/adoptium/documentation-services/issues/2
A managed service should be created that can download the branch to a temp file and provides access (read) to such temp files. Based on that service a HTTP endpoint must be created that just returns static files from the temp folder.
Attention: https://github.com/adoptium/documentation-services/issues/1 must be solved before this issue can be started since we need the basic setup of the Java service.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by AdhaarSharma** [comment]
I know Java but I think just knowing Java will be inadequate to fix the issue. I want to know what exactly do I need to learn. Do I have to learn Java RESTful webservices or Spring Boot or something else? I didn't exactly understand what you meant when you asked to create a managed service. 
Looking forward to my first pull request.

**Comment by hendrikebbers** [comment]
I started to work on a first version of the (metadata) model that can be created based on the adoc files: https://github.com/adoptium/documentation-services/issues/19
